# Generated by Django 5.2.15 on 2026-10-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_pagecollection_page_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecollection',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
