# Generated by Django 5.2.15 on 2026-10-06 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_workspace_markdown_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('tier', models.CharField(choices=[('readonly', 'Read Only'), ('writer', 'Writer'), ('ledger', 'Ledger')], default='readonly', max_length=20)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('profile', models.CharField(default='compass-ai', max_length=255)),
                ('web_access', models.BooleanField(default=False)),
                ('trusted_urls', models.JSONField(blank=True, default=list)),
                ('writable_paths', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memberships', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('service_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_members', to='db.apitoken')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Agent Member',
                'verbose_name_plural': 'Agent Members',
                'db_table': 'agent_members',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting Approval'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('plan', models.TextField(blank=True)),
                ('session_ref', models.CharField(blank=True, max_length=255)),
                ('artifacts', models.JSONField(blank=True, default=list)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='db.issue')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='db.agentmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_agent_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'db_table': 'agent_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='agentmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='unique_agent_member_name_per_project'),
        ),
    ]
