# Generated by Django 5.2.15 on 2026-10-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_agent_member_agent_run'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ('pending', 'awaiting_approval', 'running'))), fields=('issue',), name='unique_unfinished_agent_run_per_issue'),
        ),
    ]
