# Generated by Django 5.2.15 on 2026-10-08 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_agent_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('instructions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('definitions', models.ManyToManyField(blank=True, related_name='groups', to='db.agentdefinition')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_groups', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Agent Group',
                'verbose_name_plural': 'Agent Groups',
                'db_table': 'agent_groups',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='agentmember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='db.agentgroup'),
        ),
        migrations.AddConstraint(
            model_name='agentgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='unique_agent_group_name_per_workspace'),
        ),
    ]
